/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as mahasiswaRouteRouteImport } from './routes/(mahasiswa)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as mahasiswaKrsPengisianRouteImport } from './routes/(mahasiswa)/krs.pengisian'
import { Route as mahasiswaKrsLihatRouteImport } from './routes/(mahasiswa)/krs.lihat'

const mahasiswaDashLazyRouteImport = createFileRoute('/(mahasiswa)/dash')()

const mahasiswaRouteRoute = mahasiswaRouteRouteImport.update({
  id: '/(mahasiswa)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mahasiswaDashLazyRoute = mahasiswaDashLazyRouteImport
  .update({
    id: '/dash',
    path: '/dash',
    getParentRoute: () => mahasiswaRouteRoute,
  } as any)
  .lazy(() => import('./routes/(mahasiswa)/dash.lazy').then((d) => d.Route))
const authLoginRoute = authLoginRouteImport
  .update({
    id: '/(auth)/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/login.lazy').then((d) => d.Route))
const mahasiswaKrsPengisianRoute = mahasiswaKrsPengisianRouteImport.update({
  id: '/krs/pengisian',
  path: '/krs/pengisian',
  getParentRoute: () => mahasiswaRouteRoute,
} as any)
const mahasiswaKrsLihatRoute = mahasiswaKrsLihatRouteImport.update({
  id: '/krs/lihat',
  path: '/krs/lihat',
  getParentRoute: () => mahasiswaRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof mahasiswaRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/dash': typeof mahasiswaDashLazyRoute
  '/krs/lihat': typeof mahasiswaKrsLihatRoute
  '/krs/pengisian': typeof mahasiswaKrsPengisianRoute
}
export interface FileRoutesByTo {
  '/': typeof mahasiswaRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/dash': typeof mahasiswaDashLazyRoute
  '/krs/lihat': typeof mahasiswaKrsLihatRoute
  '/krs/pengisian': typeof mahasiswaKrsPengisianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(mahasiswa)': typeof mahasiswaRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(mahasiswa)/dash': typeof mahasiswaDashLazyRoute
  '/(mahasiswa)/krs/lihat': typeof mahasiswaKrsLihatRoute
  '/(mahasiswa)/krs/pengisian': typeof mahasiswaKrsPengisianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dash' | '/krs/lihat' | '/krs/pengisian'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dash' | '/krs/lihat' | '/krs/pengisian'
  id:
    | '__root__'
    | '/'
    | '/(mahasiswa)'
    | '/(auth)/login'
    | '/(mahasiswa)/dash'
    | '/(mahasiswa)/krs/lihat'
    | '/(mahasiswa)/krs/pengisian'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  mahasiswaRouteRoute: typeof mahasiswaRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(mahasiswa)': {
      id: '/(mahasiswa)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mahasiswaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(mahasiswa)/dash': {
      id: '/(mahasiswa)/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof mahasiswaDashLazyRouteImport
      parentRoute: typeof mahasiswaRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(mahasiswa)/krs/pengisian': {
      id: '/(mahasiswa)/krs/pengisian'
      path: '/krs/pengisian'
      fullPath: '/krs/pengisian'
      preLoaderRoute: typeof mahasiswaKrsPengisianRouteImport
      parentRoute: typeof mahasiswaRouteRoute
    }
    '/(mahasiswa)/krs/lihat': {
      id: '/(mahasiswa)/krs/lihat'
      path: '/krs/lihat'
      fullPath: '/krs/lihat'
      preLoaderRoute: typeof mahasiswaKrsLihatRouteImport
      parentRoute: typeof mahasiswaRouteRoute
    }
  }
}

interface mahasiswaRouteRouteChildren {
  mahasiswaDashLazyRoute: typeof mahasiswaDashLazyRoute
  mahasiswaKrsLihatRoute: typeof mahasiswaKrsLihatRoute
  mahasiswaKrsPengisianRoute: typeof mahasiswaKrsPengisianRoute
}

const mahasiswaRouteRouteChildren: mahasiswaRouteRouteChildren = {
  mahasiswaDashLazyRoute: mahasiswaDashLazyRoute,
  mahasiswaKrsLihatRoute: mahasiswaKrsLihatRoute,
  mahasiswaKrsPengisianRoute: mahasiswaKrsPengisianRoute,
}

const mahasiswaRouteRouteWithChildren = mahasiswaRouteRoute._addFileChildren(
  mahasiswaRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  mahasiswaRouteRoute: mahasiswaRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
